### ISSUE TITLE
Saving service description saves desc two times - page reload fixes issue

### ISSUE THREAD

**Issue by kyyberi** [Digipalvelutehdas/dipor-dashboard#342] opened 2016-05-11 03:52 UTC
# Service desc saving doubles text
When editing service description an error happens. Editing goes fine, but after clicking save, the result shown is given text twice. 

# Steps to reproduce
0. Login
1. Open service page https://dashboard.digipalvelutehdas.fi/service/HA6WWnweFxT486FcW
2. Click edit
3. Edit text
4. Click save
5. Reload page fixes issue. 

# Observed behavior
Copies the user given text and shows it twice in description. After reloading the page, text is just once. 

# Expected behavior
Show user given description text. 

# Environment
* Web browser: firefox 42
* Operating system: windows 

**Note:** Some of the above details will be added during the discussion and testing process.

**Comment by bajiat** [comment] 2016-05-11 07:02
Closing this as duplicate of #337.

**Closed** 2016-05-11 07:02 UTC
Labels: bug, duplicate
